apiVersion: apps/v1
kind: Deployment
metadata:
  name: frozenyogurtshop
  labels:
    app: frozenyogurtshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frozenyogurtshop
  template:
    metadata:
      labels:
        app: frozenyogurtshop
    spec:
      containers:
      - name: frozenyogurtshop
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frozenyogurtshop
spec:
  selector:
    app: frozenyogurtshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
